List<String> productCategories = [
  "Mobile",
  "Essentials",
  "Appliances"
  "Sunglasses",
  "Books",
  "Fashion"
  "Watches",
  "Apparel",
  "Shoes",
  "Jewelry",
  "Bags & Luggage",
  "Handbags",
  "Kids Apparel",
  "Daily Essentials",
  "HPC",
  "Toys",
  "Pets",
  "Grocery",
  "Baby",
  "Bty",
  "Combo Offers",
  "Pharmacy",
  "Outdoors",
  "Home",
  "Kitchen",
  "Sports",
  "Automotive",
  "Industrial & Scientific",
  "Home Improvement",
  "Lawn & Garden",
  "Furniture",
  "Electronics, Appliances & Accessories",
  "All Electronics",
  "TV",
  "PC",
  "Camera",
  "Small Appliances",
  "Musical Instruments",
  "PCA",
  "Stationery Coupons",
  "TV & Appliances",
  "Books",
  "Video Games",
  "Movies",
  "Launchpad",
  "SNS",
  "PB",
  "Karigor"
];
